{{- if .Values.https.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cert-secret
type: Opaque
data:
  {{base .Values.https.certLocation }}: |-
    {{ .Values.https.certPfxAsB64 }}
{{- end }}    